services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_nest
    ports:
      - '5433:5432'
    volumes:
      - pgData:/var/lib/postgresql/data
volumes:
  pgData: